# Generated by Django 3.1.4 on 2020-12-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundooapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
